vm_ip_address: 192.168.100.150
vm_memory: 8192 
vm_cpu: 4

# This will define what ELK Stack version which we want to run.
# Setting this ensures that Elasticsearch, Logstash, Kibana and Filebeat are all the same version 
master_elk_version: '6.x'

# What rabbit queues we want to create on the system 
rabbit_queues:
  - default 


# Enables or disables the serveices on an initial vagrant up
enable_elasticsearch: true
enable_logstash: true 
enable_filebeat: true 
enable_rabbitmq: true 
enable_kibana: true 
enable_grafana: true 
enable_cerebro: true 