vm_ip_address: 192.168.100.150
vm_memory: 4096
vm_cpu: 4

# This will define what ELK Stack version which we want to run.
# Setting this ensures that Elasticsearch, Logstash, Kibana and Filebeat are all the same version 
master_elk_version: '6.x'

# What rabbit queues we want to create on the system 
rabbit_queues:
  - default 
